// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./../components/Button.vue')['default']
    ExternalLink: typeof import('./../components/ExternalLink.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    IconMdiGithub: typeof import('~icons/mdi/github')['default']
    IconMdiHeadHeart: typeof import('~icons/mdi/head-heart')['default']
    IconMdiInstagram: typeof import('~icons/mdi/instagram')['default']
    IconMdiTwitter: typeof import('~icons/mdi/twitter')['default']
    IconRiMoonLine: typeof import('~icons/ri/moon-line')['default']
    IconRiSunLine: typeof import('~icons/ri/sun-line')['default']
    MarkdownPage: typeof import('./../components/MarkdownPage.vue')['default']
    Navigation: typeof import('./../components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TerminalWindow: typeof import('./../components/TerminalWindow.vue')['default']
    WiggleAnimation: typeof import('./../components/WiggleAnimation.vue')['default']
  }
}
